# BuyCommand configuration
# Version number of configuration - do not touch! It is used for automatic updates of configuration settings. 
version: 1
# Language - reads configuration from specific language file
language: en
settings:
# Check for updates on server start (output notification to server console, your server has to connect to remote server to check version numbers)
    updateNotificationOnStart: true
# Check for updates whenever an operator or user with the right buycommand.admin logs in (your server has to connect to remote server to check version numbers)
    updateNotificationOnLogin: true
