# BuyCommand configuration
# Version number of configuration - do not touch! It is used for automatic updates of configuration settings. 
version: 1
# Language - reads configuration from specific language file
language: en
settings:
# Check for updates on server start (output notification to server console, your server has to connect to remote server to check version numbers)
    updateNotificationOnStart: true
# Check for updates whenever an operator or user with the right buycommand.updatenotify logs in (your server has to connect to remote server to check version numbers)
    updateNotificationOnLogin: true
# Should ops be charged, too?
    chargeOps: true
# Commands are set up in a list
# The keys can be set freely, but must be unique
# Each key contains command and costs (which can be negative, if players should actually recieve money for certain commands)
# You can also set "only" or "except" keys which can contain a single permission or a list of permissions
commands:
    1:
         command: '^/tp'
         cost: 10
    2:
         command: '^/spl join'
         cost: -25.0
         only: simplespleef.admin
    spleefstart:
         command: '^/spl start'
         cost: 1
         except:
            - simplespleef.admin
            - someother.permission